# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unlesee you know exactly what you are doing)
enable_modelarts: False
# Url for modelarts
data_url: ""
train_url: ""
ckpt_url: ""
result_url: ""
# path for local
data_dir: "/cache/data"
train_dir: "/cache/train"
result_dir: "/cache/output"
ckpt_dir: "/cache/checkpoint.ckpt"
device_target: "Ascend"

# ======================================================================================
# common options
run_distribute: False

# ======================================================================================
# Training options
dataset : "kegg"
save_checkpoint_steps: 1000
keep_checkpoint_max: 30
save_checkpoint_path: "./ckpt/"
RAW_DATA_DIR : 'raw_data/'
PROCESSED_DATA_DIR : 'data/'

neighbor_sample_size: 4
embed_dim: 32
n_depth: 2
l2_weight: 0.0000001
lr: 0.0005
batch_size: 2048
aggregator_type: "concat"
n_epoch: 12
optimizer: "adam"

# ======================================================================================
# Eval options
checkpoint_path: "./ckpt/ckpt_0/kgnn-23_32.ckpt"

# ======================================================================================
# export options
device_id: 0
file_name: "KGNN"
file_format: "MINDIR"
# ======================================================================================
#postprocess
ann_file: ""
result_path: ""

---
# Help description for each configuration
enable_modelarts: "Whether training on modelarts default: False"
data_url: "Url for modelarts"
train_url: "Url for modelarts"
ckpt_url: "Url for checkpoint"
result_url: "Url for result"
data_dir: "The directory of data"
train_dir: "The directory of train"
result_dir: "The directory of result"
ckpt_dir: "The directory of checkpoint"
device_target: "device id of GPU or Ascend. (Default: None)"
run_distribute: "Run distribute, default is false."
dataset: "choices [kegg, drugbank]"
save_checkpoint_path: "The path of saving checkpoint"
RAW_DATA_DIR: "The directory of raw data"
PROCESSED_DATA_DIR: "The directory of processed data"
checkpoint_path: "checkpoint file path, default is None"
file_format: "choices [AIR, ONNX, MINDIR]"
