block_deletion:
  msa_fraction_per_block: 0.3
  num_blocks: 5
  randomize_num_blocks: true
common:
  distillation: false
  replace_proportion: 0.0
  masked_msa:
    profile_prob: 0.1
    same_prob: 0.1
    uniform_prob: 0.1
  max_extra_msa: 1024
  msa_cluster_features: true
  num_recycle: 4
  reduce_msa_clusters_by_max_templates: true
  resample_msa_in_recycling: true
  use_templates: true
  template_features:
  - template_all_atom_positions
  - template_sum_probs
  - template_aatype
  - template_all_atom_masks
  - template_domain_names
  unsupervised_features:
  - aatype
  - residue_index
  - sequence
  - msa
  - domain_name
  - num_alignments
  - seq_length
  - between_segment_residues
  - deletion_matrix
  - template_all_atom_positions
  - template_sum_probs
  - template_aatype
  - template_all_atom_masks
  - template_domain_names

eval:
  crop_size: 256
  fixed_size: true
  masked_msa_replace_fraction: 0.15
  max_msa_clusters: 128
  max_templates: 4
  num_ensemble: 1
  subsample_templates: true
  keep_extra: True