seq_length : 384
soft_temp : 1.0
soft_etemp : 1.0
soft_hard : 0.0
temp_value : 1.0
temp_decay : 0.01
temp_soft : 1.0
temp_esoft : 1.0
temp_hard : 0.0
temp_ehard : 0.0
hard_soft : 1.0
hard_esoft : 1.0
hard_temp : 0.01
hard_etemp : 0.01
hard_value : 1.0
hard_decay : 1.0
fixbb:
  con: 0.0
  plddt: 0.0
  exp: 0.0
  pae: 0.0
  fape: 1.0
  seq: 0.0
  rmsd: 0.0
  dgram: 0.0
  rg: 0.0
hallu:
  con: 1.0
  plddt: 0.0
  exp: 0.0
  pae: 0.0
  fape: 0.0
  seq: 0.0
  rmsd: 0.0
  dgram: 0.0
  rg: 0.0
opt_alpha: 2.0
opt_bias: 0.0
opt_use_pssm: False
